# Generated by Django 4.2.11 on 2024-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
