# Generated by Django 4.2.11 on 2024-04-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
