# Generated by Django 4.2.11 on 2024-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_crew_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='content',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='content2',
        ),
        migrations.AddField(
            model_name='crew',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
