# Generated by Django 4.2.11 on 2024-05-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_crew_content_remove_crew_content2_crew_title2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content2',
            new_name='inside_content',
        ),
    ]
