# Generated by Django 4.2.11 on 2024-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_content2_blogpost_inside_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='inside_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
